# Generated by Django 4.0.10 on 2023-04-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='unlocked', max_length=12)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet')),
            ],
        ),
    ]
