# Generated by Django 4.0.10 on 2023-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='latitude',
            field=models.FloatField(default=52.377956, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='longitude',
            field=models.FloatField(default=4.89707, max_length=20),
            preserve_default=False,
        ),
    ]
